spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starter_demo?serverTimezone=UTC
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #му╥Е